baseurl: "/koalition2021" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

collections:
  chapters:
    output: true
    permalink: /kapitel/:name/
    layout: chapter

defaults:
  - scope:
      path: ""
      type: "chapters"
    values:
      layout: "chapter"
      title:
      section:
      statements:
      - summary:
        id:
        categories:
        status: "not_implemented"
        last_update:
        reports:
        - title:
          url:

# Build settings
markdown: kramdown

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - scripts/
  - requirements.txt
